<?php

namespace Act\ResourceBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Application\Sonata\UserBundle\Entity\User as AppUser;

/**
 * TeamProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamProjectRepository extends EntityRepository
{
    /**
     * Récupère les projets configurés pour un utilisateur donné, ordonnés
     * @param AppUser $u
     * @param Team    $t
     */
    public function getTeamProject(AppUser $u, Team $t)
    {
        $qb = $this->createQueryBuilder('tp')
                ->join('tp.projects', 'projs')
                ->where('tp.user = :user')
                ->andWhere('tp.team = :team')
                ->addSelect('projs')
                ->setParameter('user', $u)
                ->setParameter('team', $t);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
