imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_user.yml }

parameters:
    # overrides for console commands
    router.request_context.host: %host%
    router.request_context.scheme: http
    router.request_context.base_url: ~

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }


framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:      
        engines: ['twig']
        assets_version: v1.4
        assets_base_urls: 
            http: [%router.request_context.scheme%://%router.request_context.host%]
            ssl: [%router.request_context.scheme%://%router.request_context.host%]
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        cookie_lifetime: 86400  # time in seconds - here 24 hours
    fragments:       ~
    validation: { enable_annotations: true }
    serializer:
        enabled: true

    
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        version: 1.4
    form:
        resources:
            - 'ActResourceBundle:Form:fields_errors.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        
        - ActResourceBundle
        - ApplicationSonataUserBundle
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        sass: ~
        compass: ~


# Doctrine Configuration
doctrine:
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            restricted:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %restricted_user%
                password: %restricted_password%
                charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType


# Swiftmailer Configuration
swiftmailer:
    transport: mail


# FOSUserBundle
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager


# JMSI18nRoutingBundle
jms_i18n_routing:
    default_locale: fr
    locales:        [fr, en]
    strategy:       prefix


# doctrine extensions
stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
            timestampable: true


knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default
